package DAL;
// Generated Oct 17, 2017 2:03:50 PM by Hibernate Tools 4.3.1



/**
 * Bedrijven generated by hbm2java
 */
public class Bedrijven  implements java.io.Serializable {


     private Integer id;
     private String naam;
     private String userId;
     private String paswoord;
     private String email;
     private String telefoon;

    public Bedrijven() {
    }

    public Bedrijven(String naam, String userId, String paswoord, String email, String telefoon) {
       this.naam = naam;
       this.userId = userId;
       this.paswoord = paswoord;
       this.email = email;
       this.telefoon = telefoon;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNaam() {
        return this.naam;
    }
    
    public void setNaam(String naam) {
        this.naam = naam;
    }
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }
    public String getPaswoord() {
        return this.paswoord;
    }
    
    public void setPaswoord(String paswoord) {
        this.paswoord = paswoord;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getTelefoon() {
        return this.telefoon;
    }
    
    public void setTelefoon(String telefoon) {
        this.telefoon = telefoon;
    }




}


