package DAL;
// Generated Oct 17, 2017 2:03:50 PM by Hibernate Tools 4.3.1



/**
 * Stageplaatsen generated by hbm2java
 */
public class Stageplaatsen  implements java.io.Serializable {


     private Integer id;
     private String naam;
     private String email;
     private String adres;
     private String postcode;
     private String beschrijving;
     private int bedrijvenId;

    public Stageplaatsen() {
    }

    public Stageplaatsen(String naam, String email, String adres, String postcode, String beschrijving, int bedrijvenId) {
       this.naam = naam;
       this.email = email;
       this.adres = adres;
       this.postcode = postcode;
       this.beschrijving = beschrijving;
       this.bedrijvenId = bedrijvenId;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNaam() {
        return this.naam;
    }
    
    public void setNaam(String naam) {
        this.naam = naam;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getAdres() {
        return this.adres;
    }
    
    public void setAdres(String adres) {
        this.adres = adres;
    }
    public String getPostcode() {
        return this.postcode;
    }
    
    public void setPostcode(String postcode) {
        this.postcode = postcode;
    }
    public String getBeschrijving() {
        return this.beschrijving;
    }
    
    public void setBeschrijving(String beschrijving) {
        this.beschrijving = beschrijving;
    }
    public int getBedrijvenId() {
        return this.bedrijvenId;
    }
    
    public void setBedrijvenId(int bedrijvenId) {
        this.bedrijvenId = bedrijvenId;
    }




}


