package DAL;
// Generated Oct 17, 2017 2:03:50 PM by Hibernate Tools 4.3.1

import javax.ejb.Stateful;




/**
 * Studententabel generated by hbm2java
 */
@Stateful
public class Studententabel  implements java.io.Serializable {


     private Integer id;
     private String voornaam;
     private String achternaam;
     private String email;
     private String userId;
     private String paswoord;
     private String provincie;

    public Studententabel() {
    }

    public Studententabel(String voornaam, String achternaam, String email, String userId, String paswoord, String provincie) {
       this.voornaam = voornaam;
       this.achternaam = achternaam;
       this.email = email;
       this.userId = userId;
       this.paswoord = paswoord;
       this.provincie = provincie;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getVoornaam() {
        return this.voornaam;
    }
    
    public void setVoornaam(String voornaam) {
        this.voornaam = voornaam;
    }
    public String getAchternaam() {
        return this.achternaam;
    }
    
    public void setAchternaam(String achternaam) {
        this.achternaam = achternaam;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }
    public String getPaswoord() {
        return this.paswoord;
    }
    
    public void setPaswoord(String paswoord) {
        this.paswoord = paswoord;
    }
    public String getProvincie() {
        return this.provincie;
    }
    
    public void setProvincie(String provincie) {
        this.provincie = provincie;
    }




}


